{% set dpcpp_version = ">=2024.2" %}

package:
    name: numba-mlir
    version: {{ GIT_DESCRIBE_TAG }}

source:
    path: ../..

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    script_env:
        - LLVM_PATH
        - LEVEL_ZERO_DIR
        - LEVEL_ZERO_VERSION_CHECK_OFF
        - NUMBA_MLIR_USE_SYCL

requirements:
    build:
        - conda-forge::{{ compiler('cxx') }}
        - https://software.repos.intel.com/python/conda/::dpcpp-cpp-rt {{ dpcpp_version }}
        - https://software.repos.intel.com/python/conda/::{{ compiler('dpcpp') }}  =2024.2  # [not osx]
        - sysroot_linux-64 >=2.17  # [linux]
        - cmake >=3.23
        - ninja
    host:
        - https://software.repos.intel.com/python/conda/::mkl-devel {{ dpcpp_version }}
        - https://software.repos.intel.com/python/conda/::mkl-devel-dpcpp {{ dpcpp_version }}
        - https://software.repos.intel.com/python/conda/::mkl {{ dpcpp_version }}
        - https://software.repos.intel.com/python/conda/::mkl-dpcpp {{ dpcpp_version }}
        - https://software.repos.intel.com/python/conda/::dpcpp-cpp-rt {{ dpcpp_version }}
        - tbb-devel >=2021.6.0
        - level-zero-devel
        - numba >=0.59.1, <0.60
        - pybind11
        - python
        - setuptools
        - wheel
        - zlib
    run:
        - https://software.repos.intel.com/python/conda/::mkl
        - https://software.repos.intel.com/python/conda/::mkl-dpcpp {{ dpcpp_version }}
        - numba >=0.59.1, <0.60
        - packaging
        - python
        - tbb >=2021.6.0

test:
    requires:
        - pytest
        - pytest-xdist
        - scikit-learn
        - scipy
    files:
        - run_package_tests.py
    commands:
        - python run_package_tests.py verbose smoke
